name: core_platform
version: "2.1.0"
config-version: 2

profile: "snowflake"
require-dbt-version: ">=1.6.0"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"

query-comment: "=====Customer comments: {{ query_comment(node) }}===="

models:
  core_platform:
    staging:
      +materialized: view
      +required_tests: {"unique.*|not_null": 2}
    marts:
      +materialized: table      
      +required_tests: {"unique.*|not_null": 1}
      intermediate:
        +required_tests: {"unique.*|not_null": 0}
